apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cloudOps
  description: The Cloud Infrastructure team combines infrastructure, operations, governance, any remaining data center operations, architects, security, storage, networking, and help desk teams into an ecosystem that helps build and maintain the virtualized platform.
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: cloudOps@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: parul.aggarwal
spec:
  profile:
    # Intentional no displayName for testing
    email: parul@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [cloudOps]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: spandan.saha
spec:
  profile:
    displayName: Janelle Dawe
    email: spandan@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [cloudOps]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ekamdeep
spec:
  profile:
    displayName: Ekamdeep
    email: ekamdeep@example.com
    picture: https://avatars.dicebear.com/api/avataaars/nigel-manning@example.com.svg?background=%23fff
  memberOf: [cloudOps]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: niharika-zirvi
spec:
  profile:
    displayName: Niharika Zirvi
    email: niharika@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [cloudOps]
